[package]
name = "magnet"
version = "0.0.1"
edition = "2021"
authors = ["r3drun3@noneofyourbusiness.com"]
description = "Magnet â€” purple-team telemetry & simulation toolkit."

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.1"
clap = { version = "4.4", features = ["derive"] }
regex = "1.10"
hostname = "0.4"
winapi = { version = "0.3.9", features = ["winuser", "memoryapi"] }
image = "0.25.8"


[lib]
name = "magnet"
path = "src/lib.rs"
